# Generated by Django 5.1.2 on 2024-11-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('not_available', 'Not available')], default='2024-11-03', max_length=20),
            preserve_default=False,
        ),
    ]
